"use client"

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

 const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { SessionProvider } from "next-auth/react";
import { ToastContainer } from "react-toastify";
import Banner from "../../components/banner/BannerBar"
import {Provider} from "react-redux"
import {store} from "./store"
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <SessionProvider>
        <Provider store={store}>
      <body>
        <Banner/>
        <ToastContainer/>
        {children}
        </body>
        </Provider>
        </SessionProvider>
    </html>
  );
}
