// File: components/changePasswordStyles.js
export const changePasswordStyles = {
  root: {
    width: '100%',
    minHeight: '100vh',
    bgcolor: '#eef6fb',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  header: {
    width: '100%',
    background: '#890eeeff',
    color: '#fff',
    py: 10,
    px: 2,
    textAlign: 'center',
    mb: 4,
    boxShadow: 1,
    '& h5': { fontWeight: 700 },
  },
  container: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    px: 2,
     mb: 4,
  },
  card: {
    width: { xs: '95%', sm: '540px', md: '420px' },
    bgcolor: '#fff',
    borderRadius: 2,
    boxShadow: 3,
    p: { xs: 2, sm: 4 },
    display: 'flex',
    flexDirection: 'column',
    gap: 1,
  },
  submitBtn: {
    mt: 1,
    background: '#890eeeff',
    color: '#fff',
    '&:hover': { opacity: 0.95 },
    textTransform: 'none',
  },
};